apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app
  labels:
    app: my-app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: a.domain.com
    http:
      paths:
      - backend:
          serviceName: my-app-a-v2
          servicePort: 80
  - host: b.domain.com
    http:
      paths:
      - backend:
          serviceName: my-app-b-v2
          servicePort: 80
